### ISSUE TITLE
Support for Arch Linux

### ISSUE THREAD

**Issue by Neil-seu** [Nitrux/iso-tool#8]
Do you have any plan for nomad desktop in arch linux?Atleast if you make a mkiso script for arch like ubuntu based, we can generate arch iso with the script. Nomad is awesome and very simple.

**Comment by lslvr** [comment]
Hi @Neil-seu.

I was planning to base our ISOs on Arch Linux. Currently we are a quite busy working on other areas of the system, and the Ubuntu based one is fairly stable. If you can (and want, and are so kind to :grinning: ) make us a pull-request and I will review it and continue improving it.

**Comment by Neil-seu** [comment]
Thats amazing :) But I don't know where to start. I am just hyped with your eye-candy and can't wait to see the nomad on arch repo officially. But don't know how to start. i saw the mkiso part. Is it possible to bring those packages on arch?? so that we can make a nice nomad arch iso?

**Comment by Neil-seu** [comment]
I think if nomad comes to arch repo, it will be used vastly. as it is much simpler than default kde. i was trying to do something with it. But no progress :(

**Comment by lslvr** [comment]
We could build the WHOLE distro based on Arch (I like Arch too :wink:), but, as I said, currently we have no available time to work with the mkarchiso scripts. We would have to port all of our development environment from an apt-based system to PKGBUILDs (sadly, a lot of work).

We (the Nitrux team) would have to discuss this in a more extensive way.

**Comment by Neil-seu** [comment]
I understand man :) Its okay :) At least I'm glad to see that you appreciate it :grinning: I will also keep digging though i have very little idea about these porting :laughing:

**Comment by azubieta** [comment]
Hi @Neil-seu,
as you can see Nomad Desktop is not only one app but a collection of carefully integrated apps. So in order to have it running in Arch Linux you will have to pack all of them. Also there could be some changes in the way the configurations are done, so there will be need of some patches.
About including it in the repositories, we will be glad to see our software in such distribution but right now we are busy pushing forward new things. So as @luis-lavaire said if you step up and make the packing we will assist you in what ever you need. Also we could host a repo with the packages.
Cheers

**Comment by UriHerrera** [comment]
I second @azubieta.

If you need assistance just raise an issue @Neil-seu.

**Comment by Neil-seu** [comment]
Thanks Guys.. :grin:

**Comment by lslvr** [comment]
You're welcome @Neil-seu.
